// Generated by eval/pr_eval_bot.py from data.json — do not edit by hand.
window.SPARKINFER = {
  "updated": "2026-06-25",
  "status": {
    "gpu": "RTX 5090 · sm_120 · CUDA 13",
    "model": "Qwen3-30B-A3B · Q4_K_M",
    "frontier_tps": 187.61,
    "ref_name": "llama.cpp",
    "ref_tps": 365.73,
    "vram_gb": 21.4,
    "token_match": 1.0,
    "kl": 0.136
  },
  "passes_gpu": "RTX PRO 6000",
  "passes": [
    {
      "name": "baseline",
      "what": "dequantize all 128 experts",
      "tps": 0.6
    },
    {
      "name": "fused expert",
      "what": "dequant only the routed experts (Q4_K_M)",
      "tps": 32.7
    },
    {
      "name": "decode GEMV",
      "what": "coalesced [out,in], replaces M=1 GEMM",
      "tps": 84.4
    },
    {
      "name": "CUDA graph",
      "what": "capture once, replay per token",
      "tps": 118.7
    },
    {
      "name": "flash-decoding",
      "what": "KV-split + log-sum-exp combine",
      "tps": 133
    },
    {
      "name": "fused norm",
      "what": "residual + RMSNorm",
      "tps": 134
    }
  ],
  "weights": [
    {
      "area": "kernels",
      "w": 0.42,
      "color": "#006B75"
    },
    {
      "area": "runtime",
      "w": 0.26,
      "color": "#0052CC"
    },
    {
      "area": "moe",
      "w": 0.21,
      "color": "#8250DF"
    },
    {
      "area": "bench",
      "w": 0.11,
      "color": "#5DA271"
    }
  ],
  "labels": [
    {
      "l": "XL",
      "d": "> 25% of remaining headroom",
      "c": "#0E8A16"
    },
    {
      "l": "L",
      "d": "10–25%",
      "c": "#1D76DB"
    },
    {
      "l": "M",
      "d": "3–10%",
      "c": "#8250DF"
    },
    {
      "l": "S",
      "d": "1–3%",
      "c": "#B8860B"
    },
    {
      "l": "XS",
      "d": "< 1%",
      "c": "#8A93A0"
    },
    {
      "l": "none",
      "d": "within noise — no verified gain",
      "c": "#9AA6B2"
    },
    {
      "l": "REJECT",
      "d": "failed the correctness gate",
      "c": "#B60205"
    }
  ],
  "prs": [
    {
      "num": 26,
      "title": "runtime/gguf: clamp invalid general.alignment to default (fix divide-by-zero)",
      "areas": [
        "runtime"
      ],
      "label": "none",
      "tps": 186.41,
      "delta_pct": null,
      "url": "https://github.com/gittensor-ai-lab/sparkinfer/pull/26"
    },
    {
      "num": 27,
      "title": "runtime/gguf: bounds-check tensor data region against file size (fix OOB read)",
      "areas": [
        "runtime"
      ],
      "label": "none",
      "tps": 186.42,
      "delta_pct": null,
      "url": "https://github.com/gittensor-ai-lab/sparkinfer/pull/27"
    },
    {
      "num": 28,
      "title": "moe: default split-K down + PDL on Blackwell decode",
      "areas": [
        "kernels"
      ],
      "label": "none",
      "tps": 187.06,
      "delta_pct": null,
      "url": "https://github.com/gittensor-ai-lab/sparkinfer/pull/28"
    },
    {
      "num": 4,
      "title": "kernels/attention: fix flash_prefill causal mask for seqlen_q != seqlen_kv",
      "areas": [
        "kernels"
      ],
      "label": "none",
      "tps": 184.7,
      "delta_pct": null,
      "url": "https://github.com/gittensor-ai-lab/sparkinfer/pull/4"
    },
    {
      "num": 6,
      "title": "runtime/gguf: fail loudly on bad metadata array instead of desyncing the cursor",
      "areas": [
        "runtime"
      ],
      "label": "none",
      "tps": 184.68,
      "delta_pct": null,
      "url": "https://github.com/gittensor-ai-lab/sparkinfer/pull/6"
    },
    {
      "num": 9,
      "title": "fix(runtime/gguf): reject malformed metadata arrays instead of desyncing the parse cursor",
      "areas": [
        "runtime"
      ],
      "label": "none",
      "tps": 184.67,
      "delta_pct": null,
      "url": "https://github.com/gittensor-ai-lab/sparkinfer/pull/9"
    },
    {
      "num": 11,
      "title": "runtime/gguf: bound tensor n_dims to GGML_MAX_DIMS before writing dims[]",
      "areas": [
        "runtime"
      ],
      "label": "none",
      "tps": 184.58,
      "delta_pct": null,
      "url": "https://github.com/gittensor-ai-lab/sparkinfer/pull/11"
    },
    {
      "num": 12,
      "title": "fix(runtime): make GGUF load safe when shared-expert tensors are absent",
      "areas": [
        "runtime"
      ],
      "label": "none",
      "tps": 184.61,
      "delta_pct": null,
      "url": "https://github.com/gittensor-ai-lab/sparkinfer/pull/12"
    },
    {
      "num": 13,
      "title": "fix(runtime/gguf): reject tensor n_dims > 4 instead of overflowing dims[4]",
      "areas": [
        "runtime"
      ],
      "label": "none",
      "tps": 184.61,
      "delta_pct": null,
      "url": "https://github.com/gittensor-ai-lab/sparkinfer/pull/13"
    },
    {
      "num": 14,
      "title": "fix(kernels/attention): offset flash_prefill causal mask by seqlen_kv - seqlen_q",
      "areas": [
        "kernels"
      ],
      "label": "none",
      "tps": 184.71,
      "delta_pct": null,
      "url": "https://github.com/gittensor-ai-lab/sparkinfer/pull/14"
    },
    {
      "num": 15,
      "title": "fix(runtime/qwen35): force n_shared=0 on GGUF loads without shared-expert tensors",
      "areas": [
        "runtime"
      ],
      "label": "none",
      "tps": 0.0,
      "delta_pct": null,
      "url": "https://github.com/gittensor-ai-lab/sparkinfer/pull/15"
    },
    {
      "num": 8,
      "title": "moe: PDL on the decode gate_up->down pair (gated SPARKINFER_PDL) [POC]",
      "areas": [
        "kernels"
      ],
      "label": "L",
      "tps": 187.61,
      "delta_pct": 14.5,
      "url": "https://github.com/gittensor-ai-lab/sparkinfer/pull/8"
    }
  ]
};
